blog/urls.py
from django.urls import path
from . import views
from .views import (PostListView,
                    PostDetailView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    UserPostListView)

app_name = 'blog'

urlpatterns = [
    # path('', views.home, name='home'),
    path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user_post'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('about/', views.about, name='about'),

]

django_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from blog import views as blog_views
from django.conf.urls import handler404, handler500

handler404 = blog_views.handler404
handler500 = blog_views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),

    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile ,name='profile'),

    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='post')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})
    # reverse returns the full url as a string

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.contrib.auth.models import User
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        UserPassesTestMixin)



def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    # it is looking for a template in blog/post_list.html
    #                              # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    # ordering = ['-date_posted'] we overwrite this with get_queryset
    paginate_by = 5

    def get_queryset(self):
        # looks in the url for a parameter 'username'
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post
    # it is looking for a template in blog/post_detail.html
    #                              # <app>/<model>_<viewtype>.html
    # If I don't add context_object_name then
    #   in the template I will call the 'post' ---> object
    #           !!!!


# if you go to the ...post/new url it will still let you make the post unless you inherit from LoginRequiredMixin
# It's the same as using @login_required decorator on a function
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    # it is looking for a template in blog/post_form.html .. same for UpdateView

    # overwrite the form_valid method to add the author
    # before the form is submitted
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    # success_url = '' to redirect to a certain template after the form was submitted successfully
    # or make the get_absolute_url function inside the model



# add UserPassesTestMixin to let the users edit only their OWN posts
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    # it is looking for a template in blog/post_form.html ... same for CreateView

    # overwrite the form_valid method to add the author
    # before the form is submitted
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    # success_url = '' to redirect to a certain template after the form was submitted successfully
    # or make the get_absolute_url function inside the model

    # UserPassesTestMixin will run this function to see if our user passes a certain test condition
    # get_object is a method of PostUpdateView
    def test_func(self):
        post = self.get_object()
        # if the current user == the author of the post to update
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    # it is looking for a template in blog/ called post_confirm_delete.html
    success_url = '/' # send then to the homepage after deletion

    def test_func(self):
        post = self.get_object()
        # if the current user == the author of the post to update
        if self.request.user == post.author:
            return True
        return False

    # If I don't add context_object_name then
    #   in the template I will call the 'post' ---> object
    #  just like in the DetailView



def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


# CUSTOM ERRORS
def handler404(request, exception=None):
    return render(request, 'blog/404.html', status=404)
def handler500(request, exception=None):
    return render(request, 'blog/500.html', status=500)

blog/templates/blog/505.html
<h1>NOOO  500  :)</h1>

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
  <h1>About Page</h1>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">

    {% if title %}
      <title>Django Blog - {{ title }}</title>
    {% else %}
      <title>Django Blog</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog:home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'blog:post_create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          <!-- messages -->
          {% if messages %}
            {% for message in messages %}
            <!-- message.tags are the 5 levels of messages: debug, error... -->
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}

          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
  {% for post in posts %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'blog:user_post' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">{{ post.date_posted | date:"H:i, d F, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}

  {% if is_paginated %}

    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    <!-- get the paginator object of the current page and loop over all pages -->
    {% for num in page_obj.paginator.page_range %}
      <!-- ex:  3 4 5 '6' 7 8 9  current page is 6 -->
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}

{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Post</legend>
        <h2>Are you sure you want to delete the post "{{ object.title }}"?</h2>
      </fieldset>
      <div class="form-group">
        <button type="submit" class="btn btn-outline-danger">Yes, Delete</button>
        <a class="btn btn-outline-secondary" href="{% url 'blog:post_detail' object.id %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}" alt="">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'blog:user_post' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted | date:"H:i, d F, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post_update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post_delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Blog Post</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Post</button>
      </div>
    </form>
  </div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block content %}
  <!-- to get the value(the user) passed in the url -->
  <h1 class="mb-3" >Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>

  {% for post in posts %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'blog:user_post' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">{{ post.date_posted | date:"H:i, d F, Y" }}</small>
        </div>
        <h2><a class="article-title" href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}

  {% if is_paginated %}

    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    <!-- get the paginator object of the current page and loop over all pages -->
    {% for num in page_obj.paginator.page_range %}
      <!-- ex:  3 4 5 '6' 7 8 9  current page is 6 -->
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}

{% endblock content %}